name: Build PolicyFastGPT images in Personal warehouse

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/app/**'
      - 'packages/**'
    branches:
      - 'main'

jobs:
  build-policyfastgpt-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Alibaba Cloud Docker Registry
        run: |
           docker login registry.cn-beijing.aliyuncs.com -u henceforth1974 -p xiaoDA11
      - name: Set DOCKER_REPO_TAGGED based on branch or tag
        run: |
          echo "DOCKER_REPO_TAGGED=registry.cn-beijing.aliyuncs.com/henceforth1974/policyfastgpt:latest" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          docker build -f ./projects/app/Dockerfile \
          -t registry.cn-beijing.aliyuncs.com/closeai/policygpt:v5local \
          --build-arg name=app \
          --build-arg proxy=taobao \
          .
      - name: Push Docker Image to Alibaba Cloud Registry
        run: |
          docker push registry.cn-beijing.aliyuncs.com/closeai/policygpt:v5local
